# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

author: Raquel y Javier
title: Boda de Raquel y Javier
email: jcanadillacasco@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Bienvenidos a la página web de nuesta boda. Estamos muy felices de que forméis
  parte de nuestra historia y deseamos que disfrutéis con nosotros de este día tan especial
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bodaraquelyjavier.live" # the base hostname & protocol for your site, e.g. http://example.com
basefolder: f57dfbee3893dde04700f97c40ffae91d680bfc5
keywords: boda,javier,raquel,nos casamos,amor

paginate: 6
paginate_path: "f57dfbee3893dde04700f97c40ffae91d680bfc5/blog/page:num/"

show_dir_listing: false

host: 0.0.0.0
port: 4000

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      isPost: true

collections:
  f57dfbee3893dde04700f97c40ffae91d680bfc5:
    output: true
    permalink: /:collection/:name
  posts:
    output: true
    permalink: /f57dfbee3893dde04700f97c40ffae91d680bfc5/blog/:categories/:year/:month/:day/:title

exclude: ["optimizador"]
